# Generated by Django 5.1.3 on 2024-12-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('image_description', models.TextField()),
                ('image_date', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
